spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:C:/temp/h2/sample
    username: sa
    password:
  h2:
    console:
    enabled: true
    path: /h2-console
  jpa:
    properties:
      defer-datasource-initialization: true
    hibernate:
      ddl-auto: validate
      show_sql: true
      format_sql: true
  liquibase:
    change-log: db-dev/changelog/master.yaml
    contexts: init-insert, init-create
