spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/AccountingSystem?currentSchema=dev
    username: postgres
    password: 111
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    hibernate:
      ddl-auto: create-drop
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy

  liquibase:
    enabled: false