spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/AccountingSystem
    username: postgres
    password: 111
  h2:
    console:
    enabled: true
    path: /h2-console
  jpa:
    properties:
      defer-datasource-initialization: true
    hibernate:
      ddl-auto: validate
      show_sql: true
      format_sql: true
  liquibase:
    change-log: db-dev/changelog/master.yaml
    contexts: init-insert, init-create
